export const WALLPAPER_TAG_LABELS: Record<"en" | "ar", Record<string, string>> = {
  en: {
    calligraphy: "calligraphy",
    arabic: "arabic",
    waves: "waves",
    cultural: "cultural",
    ribbons: "ribbons",
    ribbon: "ribbon",
    abstract: "abstract",
    minimal: "minimal",
    white: "white",
    gradient: "gradient",
    "flag-colors": "flag colors",
    classic: "classic",
    "burj-khalifa": "burj khalifa",
    sunset: "sunset",
    "red-sky": "red sky",
    dubai: "dubai",
    skyline: "skyline",
    "black-white": "black & white",
    mosque: "mosque",
    "sheikh-zayed": "sheikh zayed",
    "abu-dhabi": "abu dhabi",
    falcon: "falcon",
    heritage: "heritage",
    flag: "flag",
    waving: "waving",
    patriotic: "patriotic",
    brushstrokes: "brushstrokes",
    artistic: "artistic",
    modern: "modern",
    dramatic: "dramatic",
    bold: "bold",
  },
  ar: {
    calligraphy: "خط عربي",
    arabic: "عربي",
    waves: "أمواج",
    cultural: "تراثي",
    ribbons: "شرائط",
    ribbon: "شريط",
    abstract: "تجريدي",
    minimal: "بسيط",
    white: "أبيض",
    gradient: "تدرّج",
    "flag-colors": "ألوان العلم",
    classic: "كلاسيكي",
    "burj-khalifa": "برج خليفة",
    sunset: "غروب",
    "red-sky": "سماء حمراء",
    dubai: "دبي",
    skyline: "أفق المدينة",
    "black-white": "أبيض وأسود",
    mosque: "مسجد",
    "sheikh-zayed": "الشيخ زايد",
    "abu-dhabi": "أبوظبي",
    falcon: "صقر",
    heritage: "تراث",
    flag: "علم",
    waving: "رفرفة",
    patriotic: "وطني",
    brushstrokes: "ضربات فرشاة",
    artistic: "فنّي",
    modern: "عصري",
    dramatic: "درامي",
    bold: "جريء",
  },
};

export function labelForTag(lang: "en" | "ar", tag: string): string {
  return WALLPAPER_TAG_LABELS[lang][tag] ?? tag;
}
